### ISSUE TITLE
phpforce/soap-client not found

### ISSUE THREAD

**Issue by omniphx** [ronnievisser/Laravel4-Salesforce-library#2]
I'm getting the following problem when I try installing this through composer:

Problem 1
    - Installation request for ronster/salesforce dev-master -> satisfiable by ronster/salesforce[dev-master].
    - ronster/salesforce dev-master requires phpforce/soap-client \* -> no matching package found.

Any suggestions?

**Comment by kilrizzy** [comment]
Having the same problem, though I don't think it's an issue with this package. What's weird is I'm having trouble just installing "phpforce/soap-client": "dev-master" directly so I'm thinking there might be a weird naming issue with that package

**Comment by ronnievisser** [comment]
I will look in to it asap..—

**Comment by kilrizzy** [comment]
Was able to get it working by installing phpforce/common manually. It seems like there's a disconnect from /soap-client to /common. Now just running into L4.1 version errors :)
